# Generated by Django 4.2.1 on 2023-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название: ')),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Красный', 'Красный'), ('Серый', 'Серый')], max_length=100, verbose_name='Цвет: ')),
                ('size', models.CharField(default='l(50)', max_length=100, verbose_name='Размер')),
                ('prise', models.IntegerField(verbose_name='')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото продукта: ')),
                ('production', models.CharField(max_length=50, verbose_name='Производство: ')),
                ('material', models.TextField(default='Хлопок', verbose_name='Материал: ')),
                ('brand', models.CharField(choices=[('Artem Shumov', 'Artem Shumov'), ('Altea', 'Altea'), ('Dal Lago', 'Dal Lago'), ('Nike', 'Nike')], max_length=100, verbose_name='Бренд:')),
            ],
        ),
    ]
