# Generated by Django 4.2.1 on 2023-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='material',
            field=models.CharField(default='Хлопок', max_length=100, verbose_name='Материал: '),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prise',
            field=models.IntegerField(verbose_name='Цена: '),
        ),
        migrations.AlterField(
            model_name='shop',
            name='size',
            field=models.CharField(default='l(50)', max_length=100, verbose_name='Размер: '),
        ),
    ]
