# Generated by Django 4.2.1 on 2023-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_shop', '0003_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.TextField(verbose_name='Ваш отзыв:'),
        ),
    ]
