# Generated by Django 4.2.1 on 2023-06-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_alter_customusers_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='work',
        ),
        migrations.AddField(
            model_name='customusers',
            name='about',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='house',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='married',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='street',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
